### ISSUE TITLE
readの戻り値

### ISSUE THREAD

**Issue by koji-hirono** [yrm006/miniscript#1]
https://github.com/yrm006/miniscript/blob/48a40f361142e0ddab49d8bb06ad1ea544245206/readme.c#L104-L106

rがsize_tなので負になることはなく、readで-1になった時はうまく判定できないものと思います。
ssize_tかintでしょうか。

**Comment by yrm006** [comment]
You are right. I'll change to int.

ほんとですね、intにします。

**Comment by yrm006** [comment]
I changed to ssize_t.

ssize_t にしました。
